language: ruby

services:
  - docker

before_install:
  - docker build --tag storage .
  - docker run -v `pwd`:/srv/host storage /bin/sh -c "gulp lint"

script:
  - docker ps -a

branches:
  only:
    - master
    - production

notifications:
  slack: wrioos:XDZWFBrf9TDtoEOcw5YGBM4a

deploy:
  - provider: s3
    access_key_id:
      secure: FUPq2g9wtMRiOFlNYWtVmU1fzKPu4OSXGtlynkmuWgMMQ0U7HnBquE/lKQPElCqrpFs5kW2zdqEqyKZNgUZPLVTENT5RDTHKCSDC90vG94n6Q+EtpX6WJbugoN7rGeJFUO72iuWX0R5o2QY97VjXsgY6ntpp8mH+EcEpet3W5sg=
    secret_access_key:
      secure: feP/uOy9aWA4Rvpz0wQptgg/vV6xoMd8B2wCBJORvPZf1DJsKnTqa69Uk2ISsY9IfVwyIszSqBqDXAY+YGUgEHorw/x6akG2HOZI8lwdkTVQccldxOExLBU4i5FMSa/8UIArTKP14n4aen7ZkyjXkBlH5BXmJPnA13aye/LxpfM=
    bucket: wrioos.com
    upload-dir: Storage-WRIO-App
    acl: public_read 